name: CI

on:
  schedule:
    - cron: '*/5 * * * *'

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          bash docs2_update_file.sh
          bash website_update_file.sh
