name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '* */3 * * *'

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run script
        env:
          CI_TOKEN: ${{ secrets.CI_TOKEN }}
          TZ: 'Asia/Shanghai'
        run: |
          bash docs2_update_file.sh
          bash website_update_file.sh
